<select id="CarModel" name="CarModel" value="<?php echo @$data['CarModel'];?>">
   <option selected="selected" value="" disabled>Select car model</option>
   <?php if (isset($CarModel)){ ?><option value = "<?php echo $CarModel;?>" selected = "selected"><?php echo $CarModel; }?></option>
   <option value="Tesla">Tesla</option>
   <option value="BMW">BMW</option>
   <option value="Ferrari">Ferrari</option>
   <option value="Ford">Ford</option>
   <option value="Porsche">Porsche</option>
   <option value="Honda">Honda</option>
   <option value="Lamborghini">Lamborghini</option>
   <option value="Toyota">Toyota</option>
   <option value="Bentley">Bentley</option>
   <option value="Maserati">Maserati</option>
   <option value="Audi">Audi</option>
   <option value="Jeep">Jeep</option>
   <option value="Subaru">Subaru</option>
   <option value="Cadillac">Cadillac</option>
   <option value="Chyrsler">Chyrsler</option>
   <option value="Chevrolet">Chevrolet</option>
   <option value="Dodge">Dodge</option>
   <option value="Hyundai">Hyundai</option>
   <option value="Jaguar">Jaguar</option>
   <option value="Mazda">Mazda</option>
   <option value="Nissan">Nissan</option>
   <option value="Alfa Romeo">Alfa Romeo</option>
   <option value="Bugatti">Bugatti</option>
   <option value="Lexus">Lexus</option>
   <option value="Rolls-Royce">Rolls-Royce</option>
   <option value="Aston Martin">Aston Martin</option>
   <option value="Chevrolet">Chevrolet</option>
   <option value="Kia">Kia</option>
   <option value="Mercedes-Benz">Mercedes-Benz</option>
   <option value="Volkswagen">Volkswagen</option>
   <option value="Volvo">Volvo</option>
   <option value="Mitsubishi">Mitsubishi</option>
   <option value="Infiniti">Infiniti</option>
   <option value="Peugeot">Peugeot</option>
   <option value="Saab">Saab</option>
   <option value="Suzuki">Suzuki</option>
   <option value="Citroen">Citroen</option>
   <option value="Fiat">Fiat</option>
   <option value="Mini Cooper">Mini Cooper</option>
   <option value="Renault">Renault</option>
   <option value="Skoda">Skoda</option>
   <option value="Opel">Opel</option>
   <option value="Seat">Seat</option>
   <option value="Dacia">Dacia</option>
   <option value="Other">Other</option>
</select>