<select id="Car" name="Cars">
   <option value="ASTON MARTIN">ASTON MARTIN</option>
   <option value="AUDI">AUDI</option>
   <option value="BENTLEY">BENTLEY</option>
   <option value="BMW">BMW</option>
   <option value="BUGATTI">BUGATTI</option>
   <option value="FERRARI">FERRARI</option>
   <option value="DAIMLERCHRYSLER">DAIMLERCHRYSLER</option>
   <option value="FORD">FORD</option>
   <option value="FUJI">FUJI</option>
   <option value="GM">GM</option>
   <option value="HONDA">HONDA</option>
   <option value="HYUNDAI">HYUNDAI</option>
   <option value="JAGUAR">JAGUAR</option>
   <option value="KIA">KIA</option>
   <option value="LAMBORGHINI">LAMBORGHINI</option>
   <option value="LAND ROVER">LAND ROVER</option>
   <option value="LOTUS">LOTUS</option>
   <option value="MASERATI">MASERATI</option>
   <option value="MAZDA">MAZDA</option>
   <option value="MERCEDES">MERCEDES</option>
   <option value="MITSUBISHI">MITSUBISHI</option>
   <option value="NISSAN">NISSAN</option>
   <option value="PORSCHE">PORSCHE</option>
   <option value="ROLLS-ROYCE">ROLLS-ROYCE</option>
   <option value="ROUSH">ROUSH</option>
   <option value="SUZUKI">SUZUKI</option>
   <option value="TOYOTA">TOYOTA</option>
   <option value="VOLKSWAGEN">VOLKSWAGEN</option>
   <option value="VOLVO">VOLVO</option>
</select>