<?php 
error_reporting(0);
?>

<!DOCTYPE html>
<html lang="RU">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Global Care - Terms and Conditions</title>
    <link rel="stylesheet" href="<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap&subset=cyrillic" rel="stylesheet"">
    <link rel="stylesheet" href="css/sample.css">
    <link rel="stylesheet" href="css/normalize.css">
</head>
<body>
    <div class="container">
        <header>
            <a class="logo" href="../index.php"><img src="../images/logo5.png" alt="logotype" class="new-logo"> </a>
            <input type="text" class="input input-address" placeholder="Search">
            <?php 
            if(!isset($_COOKIE['name']))
            { ?>
            <div class="buttons">
                <!-- ctrl / -->
                <button class="button button-primary" id="login-button">
                    <img src="../images/user.svg" alt="Log in" class="button-icon">
                    <span class="button-text">Log in</span>
                </button>
                <button class="button button-primary"  id="register-button">
                    <img src="../images/user.svg" class="button-icon"alt="Register">
                    <span class="button-text">Register</span>
                </button>
            </div>

            <?php
            } 
            else{ ?>
            <span class="welcome-message"><?php echo $_COOKIE['name'] . " " . $_COOKIE['surname'];?></span>
            <div class="buttons">
                <a href="../php/logout.php">
                    <button class="button button-primary"  id="register-button">
                    <img src="../images/user.svg" class="button-icon"alt="Register">
                    <span class="button-text">Log out</span>
                    </button>
                </a>
            </div>
            <?php } ?>
    
        </header>

        <div class="main">
            <section class="promo">
                <h1 class="promo-title">Global Care - Insruance<br>Terms and Conditions</h1>
                <p class="promo-text">Agree to our terms and conditions in order to buy product from GlobalCare!</p>
            </section>
        </div>
<center>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left;"><span style="font-size:30px;color:black;">1. Definitions</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">1.1 In these Terms and Conditions the following words and phrases have the following meanings:</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">&bull; &ldquo;GlobalCare&rdquo; or &ldquo;we&rdquo; means GlobalCare Ltd (company registration xxxxxxx) with</span>registered offices at Tallinn/Estonia.</p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; &ldquo;the Client&rdquo; means the individual, business, organisation or company identified in the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Letter of Agreement.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; &ldquo;Terms and Conditions&rdquo; are GlobalCare&rsquo;s standard terms and conditions as set out in</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">this document.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; &ldquo;Agreement&rdquo; means the agreement between the Client and GlobalCare in respect of the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">provision of Services as set out in these Terms and Conditions and the Letter of</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Agreement.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; &ldquo;Material(s)&rdquo; means all and any written articles, typescripts, proofs, reports, documents,</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">graphics, designs drawings, photographs, research, videos, audios, software, CD&rsquo;s disks</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">or any other material of whatsoever nature produced by GlobalCare in accordance with</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">the Agreement, and including the source code version of any electronic-form material.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; &ldquo;Normal Working Hours&rdquo; means Monday to Friday 9.00am to 5.30pm.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">&bull; &ldquo;The Parties&rdquo; means GlobalCare and the Client.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">&bull; &ldquo;Services&rdquo; means the services to be provided to the Client by GlobalCare pursuant to</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">these Terms and Conditions and the terms set out in the Letter of Agreement entered into</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">by GlobalCare and the Client which is likely to include the production of Material(s).</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; &ldquo;Letter of Agreement&rdquo; means a document signed by GlobalCare and the Client that</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">describes the services to be provided by GlobalCare and sets out other specific agreed</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">terms including but not limited to payment and timing for the provision of the Services.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; &ldquo;Required Items&rdquo; such information, drawings, products, documents or other prerequisites</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">required by GlobalCare from the Client as identified in the Letter of</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Agreement in order for GlobalCare to provide the Services to the Client.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">1.2 In these Terms and Conditions the singular is deemed to include the plural and vice versa.</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Provision of services FEBRUARY 2020 GlobalCare &ndash; unlocking possibilities 3</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">2. Provision of services</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">2.1 GlobalCare will provide Services to the Client in accordance with the Agreement. Whereas</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">these Terms and Conditions are deemed to constitute GlobalCare&rsquo;s standard terms and</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">conditions of business the Letter of Agreement includes terms and conditions personal to the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Client and GlobalCare. In the event of a conflict between these Terms and Conditions and</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">the Letter of Agreement the latter will prevail.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">2.2 The Client acknowledges that the Services recommended or provided to the Client by GlobalCare</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">door are done so on the basis of information and/or specifications or requirements provided</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">by the Client.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">2.3 The Client shall immediately upon request provide GlobalCare with any Required Items and</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">agrees that we will not be liable for any delay or failure to provide the Services caused by the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Client&rsquo;s failure to provide any Required Items.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">2.4 The Client shall be provided with and shall retain duplicate copies of all Materials and insure</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">these against their accidental loss or damage. All Materials shall be at the sole risk of the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Client from the time of delivery to the Client. The Client acknowledges that GlobalCare will</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">retain original Materials for its own purposes including those set out at clause 7.4 below</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">unless the provisions of clause 7.1 apply.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">2.5 Where GlobalCare provides the Client with web development services, the Client has the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">right to obtain maintenance and future development work from a different developer of their</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">own choosing, upon completion of any work by GlobalCared door under the Agreement, but we</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">reserve the right to provide the Client with an estimate and/or quote in respect of such work.</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">2.6 The Client shall not unlawfully discriminate against GlobalCare employees when receiving</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Services under the Contract either directly or indirectly on such grounds as race, colour,</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">ethnic or national origin, disability, sex or sexual orientation, religion or belief, or age.</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Commencement and duration</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">FEBRUARY 2020 GlobalCare &ndash; unlocking possibilities 4</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">3. Commencement and duration</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">3.1 Subject to the provisions of clause 2.3 above GlobalCare will start providing the Services to</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">the Client on a date agreed and identified in the Letter of Agreement but for the avoidance of</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">doubt no work will be undertaken by GlobalCare unless and until the Client signs the Letter</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">of Appointment and in so doing agrees to adhere to these Terms and Conditions.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">3.2 The estimated duration of the Services will be identified in the Letter of Agreement and in the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">event that the Parties have agreed interim payments, the various stages in respect of the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Services and the duration of each stages, and timing of interim payments, will be set out</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">either in the Letter of Agreement itself or as an addendum thereto.</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Charges and payments</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">FEBRUARY 2020 GlobalCare &ndash; unlocking possibilities 5</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">4. Charges and payments</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">4.1 The Letter of Agreement will specify the charges and related payment terms applicable to the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Client in respect of the provision of Services, which may include interim payments.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">4.2 Any estimates and/or quotes provided by GlobalCare to the client shall be valid for a period</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">of 60 days from the date specified on the quote/estimate and we reserve the right to review,</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">and if appropriate increase any such quote/estimate if a Letter of Agreement has not been</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">signed by the Client within that time limit.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">4.3 Where corrections, additions and/or alterations are required and such corrections, additions</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">and/or alterations fall outside the original estimate/quote given by GlobalCare, then we</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">reserve the right to submit a revised estimate/quote that will require written agreement by the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Parties before work can commence or continue.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">4.4 GlobalCare reserves the right to revise any estimates and/or quotes provided to the Client</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">in order to compensate for any unanticipated &lsquo;rush&rsquo; requests by the Client. In the event such</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">unanticipated &lsquo;rush&rsquo; requests by the Client, we reserve the right to charge two times our</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">standard hourly rate for time that falls outside Normal Working Hours.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">4.5 The Client shall pay GlobalCare, unless the invoice is subject to dispute and notified within</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">5 working days of receipt, within 30 days of the date of our invoice.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">4.6 The Client will be liable for interest on any outstanding invoices and or interim payments at</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">the rate of 5% per month above the Bank of England base rate (at the time of invoicing) from</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">the due date until the outstanding amount is paid in full together with any costs and expenses</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">incurred by GlobalCare in obtaining payment of such invoice.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">4.7 Where interim payments are agreed between the Client and GlobalCare, we reserve the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">right to stop all work for the Client or withhold delivery of any Material(s) in the event that the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Client fails to pay any interim payment specified in the Letter of Agreement and GlobalCare</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">shall be free to exercise its rights under clause 4.6 above.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">4.8 The client may cancel all or part of the work at any stage subject to payment of a cancellation</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">fee of 25% before delivery of development plans or 50% once work has commenced on</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">prototypes or 100% on delivery of finished work.</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Expenses</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">FEBRUARY 2020 GlobalCare &ndash; unlocking possibilities 6</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">5. Expenses</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">5.1 The Client agrees to reimburse GlobalCare for out-of-pocket expenses reasonably incurred</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">by Staff in the proper provision of the Services. Any anticipated expenses will be specified in</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">the Letter of Agreement but the Client acknowledges that there may be expenses properly</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">incurred by GlobalCare in the provision of Services to the Client that were not reasonably</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">foreseeable at the time of entering into the Agreement. Any such expenses must be detailed</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">and justified in writing at/or prior to invoicing.</span> <span style="font-size:15px;color:black;">Confidentiality</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">FEBRUARY 2020GlobalCare &ndash; unlocking possibilities 7</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left;"><span style='font-size:36px;font-family:"Calibri",sans-serif;color:black;'><br>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">6. Confidentiality</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">6.1 The Client agrees during the continuance of the provision of Services by GlobalCare to the</span> Client, and at any time thereafter, to treat as secret and confidential and not at any time forany reason to disclose, or permit to be disclosed, to any person or otherwise make use of orpermit to be made use of any unpublished information relating to our business, trade secrets,technology or other know-how, finances, published or unpublished publications, client,customer or supplier details, or any such information relating to a subsidiary, supplier,customer or client where the information was received as a result of the Agreement.</p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">6.2 GlobalCare agrees during the continuance of the provision of Services by it to the Client and</span>at any time thereafter to treat as secret and confidential and not at any time for any reason todisclose or permit to be disclosed to any person or otherwise make use of or permit to bemade use of any unpublished information relating to the Client&rsquo;s business, trade secrets,technology or other know how, plans or finances, published or unpublished publications,client, customer or supplier details, or any such information relating to a subsidiary, supplier,customer or client where the information was received as a result of the Agreement. Pleaserefer to our Information Security policy for more information.</p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">6.3 Any information, correspondence or accounts relating to the Client&rsquo;s business, and held by</span> GlobalCare is available for inspection at our premises, during normal working hoursprovided that reasonable notice is given by the Client. Title, copyright and moral rights<span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">FEBRUARY 2020 GlobalCare &ndash; unlocking possibilities 8</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">7. Title, copyright and moral rights</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">7.1 Any original Material generated by GlobalCare shall remain our absolute property until such</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">time as all or part shall be transferred to the client upon written agreement of the Parties.</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">After written agreement has been received for the release of Material to the Client, all</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">liabilities for that Material are transferred to the Client and the Client undertakes to indemnify</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">GlobalCare against any and all actions, suits, proceedings, claims, demands, awards, costs</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">and damages in respect of the transferred Material.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">7.2 Any production of Material(s) by GlobalCare for the Client is protected by the Copyright</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Designs and Patents Act of 1988 (&lsquo;the Act&rsquo;), and any statutory modification or re-enactment</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">thereof for the time being in force and the words, expressions and phrases defined in or</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">assigned or having a meaning by or under the Act or any statutory modification or reenactment</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">shall have the same meaning where used herein. For the avoidance of doubt Big</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">GlobalCare shall remain the owner of all intellectual property rights in the Material(s) unless</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">such rights are specifically transferred to the Client in the Letter of Agreement.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">7.3 GlobalCare reserves the right to refuse to publish any Material that is or is likely to be</span> interpreted as being illegal, obscene and or in breach of any intellectual property right.</p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">7.4 GlobalCare reserves the right to reproduce Material generated for the Client, under these</span> Terms and Conditions in any form for marketing purposes.</p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">7.5 GlobalCare reserves the right to place an unobtrusive logo and link to their website on any</span> work undertaken for publication on the Internet.</p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">7.6 GlobalCare reserves the right to publish any software, programs or code developed on</span> behalf of the client under a suitable Open Source license unless such right is specifically<span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">revoked in writing before development commences.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">7.7 GlobalCare asserts that it may or may not hold copyright of software, programs or code</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">used in the Services, but that it will hold an appropriate license for the use of such software,</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">programs or code.</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Warranties and indemnities</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">FEBRUARY 2020 GlobalCare &ndash; unlocking possibilities 9</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">8. Warranties and indemnities</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">8.1 GlobalCare warrants that the Services will be provided using reasonable care and skill and,</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">as far as reasonably possible, in accordance with the Agreement.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.2 The Client hereby warrants that it will be fully responsible for all claims made, all trademarks,</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">copyright materials and clearances supplied to GlobalCare throughout the provision of</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Services under the Agreement.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.3 The Client indemnifies and will keep GlobalCare indemnified on a continuing basis against</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">any and all actions, suits, proceedings, claims, demands, awards, costs and damages</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">whatsoever arising as a result of any breach or alleged breach of the warranties and</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">indemnities set out in this clause .</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.4 Subject as expressly provided in these Terms and Conditions all warranties, conditions or</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">other terms implied by statute or common law are excluded to the fullest extent permitted by</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">law and GlobalCare will not be liable to the Client for any indirect, special or consequential</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">loss or damage (whether for loss of profit or otherwise), costs, expenses or other claims for</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">compensation whatsoever (whether caused by the negligence of GlobalCare, its employees</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">or agents or otherwise) whether arising out of or in connection with the provision of the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Services to the Client.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.5 Not withstanding the provisions of clause 8.4, the entire liability of GlobalCare under or in</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">connection with the Agreement shall not exceed the total charges payable by the Client.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.6 Should any actions, suits, proceedings, claims, demands, awards, costs and damages be</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">brought against GlobalCare as a result of Material produced for the Client, under the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Agreement, the Client hereby agrees to repay any losses we may suffer.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.7 GlobalCare will not be liable to the Client or in breach of contract or otherwise for delays in</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">performing, or fails to perform, any of its obligations to the Client, if that delay or failure was</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">beyond our reasonable control.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.8 GlobalCare will not be not be liable to the Client or in breach of contract or otherwise for</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">delays in performing, or if we fail to perform, any of our obligations to the Client, or if GlobalCare</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">door delivers Material late to the Client, if that delay failure and or later delivery was caused</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">by the Client.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.9 GlobalCare does not make any level of guarantee of availability or continuity of service for</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">any web site hosting or support service(s) it may provide to the Client.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">8.10 GlobalCare does not make any level of guarantee of response time or availability of support</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">for any of its web hosting, support or other services unless specifically agreed with the Client.</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Termination</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">FEBRUARY 2020 GlobalCare &ndash; unlocking possibilities 10</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">9. Termination</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">9.1 Either party (&ldquo;the Terminating Party&rdquo;) may terminate the Agreement immediately by giving</span> written notice to the other party (&ldquo;the Other Party&rdquo;) if:</p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">&bull; The Other Party has committed a breach of any of the terms of the Agreement and that</span> breach is not capable of remedy or, in the case of a breach capable of remedy, the Other<span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Party has failed to remedy the breach within 21 days of a receipt of notice from the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Terminating Party specifying the breach and requiring its remedy; or</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; The Other Party becomes insolvent or an order is made or a resolution passed for the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">administration, winding-up or dissolution of the Other Party (otherwise than for the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">purposes of a reconstruction) or an administrative or other receiver, manager, liquidator,</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">administrator, trustee or similar officer is appointed over all or a substantial part of the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">assets of the Other Party, or the Other party enters into or proposes any composition or</span> arrangement with its creditors generally analogous to the fore going agreement.</p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">9.2 GlobalCare reserves the right to terminate the Agreement with the Client for&nbsp;</span>what ever reason<span style="font-size:15px;color:black;">&nbsp;on giving no less than fourteen days written notice to the Client, and the Client&nbsp;</span>shall be<span style="font-size:15px;color:black;">&nbsp;liable to GlobalCare for all costs and expenses incurred by us up to the date&nbsp;</span>of termination<span style="font-size:15px;color:black;">.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">9.3 Upon termination of the Agreement for whatever reason:</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">&bull; all monies owing to GlobalCare by the Client under the Agreement shall be paid by the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Client forthwith;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">&bull; GlobalCare will not be held liable for any third part costs incurred.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">9.4 In the event of GlobalCare taking the Client to court to recover any monies owed, the Client</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Agrees to pay our legal fees incurred together with any interest and costs</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">9.5 Clauses 6,7,8 and this clause 9 shall survive termination of the Agreement.</span> Miscellaneous<span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">FEBRUARY 2020 GlobalCare &ndash; unlocking possibilities 11</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:36px;color:black;">10. Miscellaneous</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;"><span style="font-size:15px;color:black;">10.1 These Terms and Conditions together with the Letter of Agreement (referred collectively</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">throughout as &ldquo;the Agreement&rdquo;) constitute the entire agreement between the Parties and</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">supersede any previous agreement or understanding whether oral or in writing between the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">parties. All other terms and conditions, express or implied by statute or otherwise, are</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">excluded to the fullest extent permitted by law.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">10.2 No variations or amendments to the Agreement will be effective unless agreed in writing and</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">signed by the Parties.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">10.3 Any notice required or permitted to be given by either party to the other under the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Agreement shall be in writing addressed to the other party at its registered office or principal</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">place of business, or such other address in England or Wales, as may at the relevant time</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">have been notified pursuant to this provision to the party giving the notice.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">10.4 No failure or delay by either party in exercising any of its rights under the Agreement shall be</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">deemed to be a waiver of that right, and no waiver by either party of any breach of the</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Agreement by the other shall be considered as a waiver of any subsequent breach of the same</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">or any other provision.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">10.5 If any provision of these Terms and Conditions and or the Agreement is held by any competent</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">authority to be invalid or unenforceable in whole or in part, the validity of the other provisions</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">of the Terms and Conditions and or the Agreement and the remainder of the provision in</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">question shall not be affected.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">10.6 The Client will not hold responsible the Supplier for loss or damage to the Client&rsquo;s</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">property by third parties.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">10.7 GlobalCare reserves the right to amend or vary these Terms and Conditions at any time on</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">giving the Client reasonable notice provided that such amendment or variation does not</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">materially affect the nature or quality of the Services provided to the Client.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">10.8 These Terms and Conditions shall be governed by and construed in all aspects in accordance</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">with the laws of England.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 12.05pt; text-align: left;"><span style="font-size:15px;color:black;">10.9 Any dispute or difference of any kind whatsoever which arises or occurs between the Parties</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">in relation to anything or matter arising under, out of or in connection with this agreement</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">shall be referred to arbitration under the Arbitration Rules of the Chartered Institute of</span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span><span style="font-size:15px;color:black;">Arbitrators.</span></p>
<p style="margin: 0in 0in 8pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 107%; text-align: left;">&nbsp;</p>
</center>
<p><br></p>
        <footer class="footer">
            <div class="container">
                <div class="footer-block">
                    <img class="footer-logo" src="../images/logo5.png" alt="logo">
                    <nav class="footer-nav">
                        <a href="" class="footer-link">Partnership</a>
                        <a href="awards.php" class="footer-link">Awards</a>
                        <a href="offices.php" class="footer-link">Offices</a>
                        <a href="contacts.php" class="footer-link">Contacts</a>
                    </nav>
                    <div class="social-links">
                        <a class="social-link" href="#"><img src="../images/inst.svg" alt="instagram"></a>
                        <a class="social-link" href="#"><img src="../images/face.svg" alt="facebook"></a>
                        <a class="social-link" href="#"><img src="../images/vk.svg" alt="vk"></a>
                    </div>
                </div>
            </div>
        </footer>

        <div class="register">
            <div class="register-dialog">
                <div class="login-close-b">
                <button class="register-close">&times;</button>
                </div>
                <div class="login-form">
                    <form id="login-form-process" action="../php/register.php" method="POST">
                            <p><input type="text" placeholder="First name" name="fname" ></p>
                            <p><input type="text" placeholder="Last name" name="lname" ></p>
                            <p><input type="email" placeholder="Email" name="email" ></p>
                            <p><input type="password" placeholder="Password" name="password"></p>
                            <p><input type="submit" value = "Register" name="register"></p>
                    </form>
                </div>
            </div>
        </div>

        <div class="login">
            <div class="login-dialog">
                <div class="login-close-b">
                    <button class="login-close">&times;</button>
                </div>
                <div class="login-form">
                    <form id="login-form-process" action="../php/login.php" method="POST">
                            <p><input type="email" placeholder="Email" name="email" ></p>
                            <p><input type="password" placeholder="Password" name="password"></p>
                            <p><input type="submit" value = "Login" name="login"></p>
                            <p id="question">Not registered? <a href="../php/register-page.php">Create an account</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="../js/wow.min.js"></script>
    <script src="../js/register.js"></script>
    <script src="../js/login.js"></script>
	
</body>
</html>